### ISSUE TITLE
Error upon executing anything

### ISSUE THREAD

**Issue by erichiller** [yunabe/tslab#26]
Hello, I've just freshly (and for the first time) installed tslab. I get an error however when I go to use it:

```
unexpected error: TypeError: notifyUpdateSrc is not a function
    at updateContent (C:\nodejs\node_modules\tslab\dist\converter.js:533:9)
    at Object.convert (C:\nodejs\node_modules\tslab\dist\converter.js:188:9)
    at Object.execute (C:\nodejs\node_modules\tslab\dist\executor.js:140:32)
    at JupyterHandlerImpl.handleExecuteImpl (C:\nodejs\node_modules\tslab\dist\jupyter.js:205:38)
    at count.execQueue.add (C:\nodejs\node_modules\tslab\dist\jupyter.js:163:57)
```

To be clear, the kernel does start. this error occurs when trying to run anything. ie `console.log('hello');`

I'm running:
* JupyterLab 1.2.4
* Windows Server Core 1809
* Python 3.7.6
* NodeJS 10.16.3

If you need any more information, let me know!

**Comment by RGFTheCoder** [comment]
Same error here
- Jupyter 4.4.0
- Windows Home 1903
- Python 3.7.0
- NodeJS v13.0.1

**Comment by yunabe** [comment]
Thanks you for the report. Because I don't have Windows environment to test tslab continuously, I did not notice there is a critical path in the path handling of tslab.

I think the most critical bug is fixed by https://github.com/yunabe/tslab/commit/792c032925158c585722eeddc975d4f88fbf5737.
If you have troubles on Windows, please let me know (or please fix them if you are interested in)

**Comment by erichiller** [comment]
I just wanted to confirm that you did fix everything, it works great now. thank you,
Eric
